spring:
  application:
    name: test.telegram.bot
  config:
    import: optional:file:.env[.properties]

bot:
  name: ${BOT_NAME}
  token: ${BOT_TOKEN}

cbr:
  exchange-rates:
    url: https://www.cbr.ru/scripts/XML_daily.asp
